describe('ParaBank Test', () => {

  it('User Sign Up', () => {
    cy.visit('https://parabank.parasoft.com/parabank/register.htm')
    cy.log("Navigated to ParaBank site")
    cy.get('input[id="customer.firstName"]').type('David')
    cy.get('input[id="customer.lastName"]').type('Jones')
    cy.get('input[id="customer.address.street"]').type('Woji')
    cy.get('input[id="customer.address.city"]').type('Port Harcourt')
    cy.get('input[id="customer.address.state"]').type('Rivers')
    cy.get('input[id="customer.address.zipCode"]').type('500101')
    cy.get('input[id="customer.phoneNumber"]').type('08020548796')
    cy.get('input[id="customer.ssn"]').type('12345678')
    cy.get('input[id="customer.username"]').type('David')
    cy.get('input[id="customer.password"]').type('20December!')
    cy.get('input[id="repeatedPassword"]').type('20December!')
    cy.get('input[value="Register"]').click()
  })

  it('User Log In', () => {
    cy.visit('https://parabank.parasoft.com/parabank/index.htm')
    cy.get('input[name="username"]').type('David')
    cy.get('input[name="password"]').type('20December!')
    cy.get('input[value="Log In"]').click()
  })

  it('User 2 Sign Up', () => {
    cy.visit('https://parabank.parasoft.com/parabank/register.htm')
    cy.log("Navigated to ParaBank site")
    cy.get('input[id="customer.firstName"]').type('Eke')
    cy.get('input[id="customer.lastName"]').type('Jones')
    cy.get('input[id="customer.address.street"]').type('Woji')
    cy.get('input[id="customer.address.city"]').type('Port Harcourt')
    cy.get('input[id="customer.address.state"]').type('Rivers')
    cy.get('input[id="customer.address.zipCode"]').type('500131')
    cy.get('input[id="customer.phoneNumber"]').type('08020546796')
    cy.get('input[id="customer.ssn"]').type('12345678')
    cy.get('input[id="customer.username"]').type('David')
    cy.get('input[id="customer.password"]').type('20December!')
    cy.get('input[id="repeatedPassword"]').type('20December!')
    cy.get('input[value="Register"]').click()
  })

  it('User 1 Pays Bill', () => {
    cy.visit('https://parabank.parasoft.com/parabank/index.htm')
    cy.get('input[name="username"]').type('David')
    cy.get('input[name="password"]').type('20December!')
    cy.get('input[value="Log In"]').click()
    cy.get('a[href="billpay.htm"]').click()
    cy.get('input[name="payee.name"]').type('Eke Jones')
    cy.get('input[name="payee.address.street"]').type('5 Ago Palace Way')
    cy.get('input[name="payee.address.city"').type('Sango')
    cy.get('input[name="payee.address.state"]').type('Lagos')
    cy.get('input[name="payee.address.zipCode"]').type('500102')
    cy.get('input[name="payee.phoneNumber"').type('08020987645')
    cy.get('input[name="payee.accountNumber"]').type('17784')
    cy.get('input[name="verifyAccount"]').type('17784')
    cy.get('input[name="amount"]').type('225')
    cy.get('input[value="Send Payment"]').click()
    cy.get('a[href="overview.htm"]').click()
  })

  it('User 1 Updates Contact Info', () => {
    cy.visit('https://parabank.parasoft.com/parabank/index.htm')
    cy.get('input[name="username"]').type('David')
    cy.get('input[name="password"]').type('20December!')
    cy.get('input[value="Log In"]').click()
    cy.get('a[href="updateprofile.htm"]').click()
    cy.wait(3000)
    cy.get('input[id="customer.address.zipCode"]').clear() 
    cy.get('input[id="customer.address.zipCode"]').type('500102')
    cy.get('input[value="Update Profile"]').click()
    cy.get('a[href="logout.htm"]').click()
  })
})